name: schedule_2
description: Schedule for easy access to zoom links.

publish_to: 'none'

version: 1.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bot_toast: ^3.0.5
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.0
  division: ^0.8.8
  firebase_auth: ^0.18.3+1
  firebase_core: ^0.5.2+1
  flutter_dropdown: ^0.0.8
  flutter_mobx: ^1.1.0+2
  lint: ^1.5.1
  mobx: ^1.2.1+4
  mobx_codegen: ^1.1.2
  provider: ^4.3.2+1
  responsive_builder: ^0.3.0
  url_launcher: ^5.7.10

dev_dependencies:
  build_runner: ^1.10.6

flutter:
  uses-material-design: true
