name: schedule_2
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  division: ^0.8.8
  firebase_auth: ^0.18.3+1
  firebase_core: ^0.5.2+1
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  provider: ^4.3.2+1
  responsive_builder: ^0.3.0
  url_launcher: ^5.7.10
  mobx_codegen: ^1.1.2

dev_dependencies:
  build_runner: ^1.10.6

flutter:
  uses-material-design: true
